apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
  - name: http
    port: 5432
    nodePort: 30950
    protocol: TCP
  selector:
   app: postgres